const express = require("express")
const router = express.Router()
const authController = require('../controllers/authControllers')
const validateMiddlewere = require('../middleware/validate')
router.post('/register' , authController.register)
router.post('/login' , authController.login)
router.post('/check',authController.checkUser)
router.patch('/updateProfile',validateMiddlewere.validateToken,authController.updateProfile)
router.delete('/deleteUser',validateMiddlewere.validateToken, authController.deleteUser)
module.exports = router