const express = require("express")
const router = express.Router()
const orderController = require('../controllers/orderControllers')
const validateMiddlewere = require('../middleware/validate')
const authMiddlewere = require('../middleware/auth')
router.get('/', orderController.getallOrder)
router.post('/addOrder',validateMiddlewere.validateToken,orderController.addOrder)
router.patch('/updateStatusOrder',validateMiddlewere.validateToken,orderController.updateStatusOrder)
router.delete('/deleteOrder/:o_ID',validateMiddlewere.validateToken,orderController.deleteOrders)
router.get(`/ordersitems/:o_ID`,validateMiddlewere.validateToken,orderController.orderitems)
router.get('/getdateEnd/:o_ID',validateMiddlewere.validateToken,orderController.getdateEnd)
router.patch(`/updateOrder`,validateMiddlewere.validateToken,orderController.updateOrder)
module.exports = router