const express = require("express")
const router = express.Router()
const orderController = require('../controllers/orderControllers')
const validateMiddlewere = require('../middleware/validate')
router.get('/',validateMiddlewere.validateToken,orderController.getallOrder)
router.get('/getOrder/:o_ID',validateMiddlewere.validateToken,orderController.getOrderID)
router.post('/addOrder',validateMiddlewere.validateToken,orderController.addOrder)
router.patch('/updateStatusOrder',validateMiddlewere.validateToken,orderController.updateStatusOrder)
router.delete('/deleteOrder/:o_ID',validateMiddlewere.validateToken,orderController.deleteOrders)
router.get(`/ordersitems/:o_ID`,validateMiddlewere.validateToken,orderController.orderitems)
router.get('/getdateEnd/:o_ID',validateMiddlewere.validateToken,orderController.getdateEnd)
router.patch(`/updateOrder`,validateMiddlewere.validateToken,orderController.updateOrder)
router.get('/sumPrice/:o_ID',validateMiddlewere.validateToken,orderController.sumPrice)
router.get('/getUserOrders',validateMiddlewere.validateToken,orderController.getUserOrders)
router.delete('/cancelOrder/:o_ID',validateMiddlewere.validateToken,orderController.cancelOrder)
module.exports = router